
// Code generated by generateconfig; DO NOT EDIT.

package config

type UserPreferences struct {
    Theme string `json:"theme,omitempty"`
    Notifications_enabled bool `json:"notifications_enabled,omitempty"`
    Preferences struct {
      Language string `json:"language,omitempty"`
      Timezone string `json:"timezone,omitempty"`
    } `json:"preferences,omitempty"`
    Username string `json:"username,omitempty"`
}
